### ISSUE TITLE
Usage of `ringo.run_confsearch`.

### ISSUE THREAD

**Issue by mseok** [TheorChemGroup/Ringo#1]
What a nice work!
I'm trying to use ringo in macrocycle conformer generation.

I've installed Ringo by pip.
Since I want to generate multiple conformations from a single code execution, I tried to use a function `run_confsearch`, although it was not presented in the README.
However, setting numthreads to either 1 or a higher integer raises error that the current build of ringo does not support any kind of Monte-Carlo search (either single-threaded or multi-threaded).
Are there any build options to use this feature?

**Comment by nkrivoshchapov** [comment]
Thank you for your kind words and interest in the program!

The repository contains the core of conformational generator that identifies independent dihedrals and enfoces them using inverse kinematics, thus, generating conformers one-by-one (see example at release_assemble/example_scripts/run_ringo.py). Currently, Monte-Carlo with refinement search discussed in JCIM paper is closed-source. In the meantime, we expect users to implement random search (naive or with refinements) on top of existing Ringo's API (either in C++ or Python) - we also mentioned this in README file of our 'mcr-benchmark' repository.
